name: 'Setup CVT'
description: 'Download CVT CLI from GitHub releases'

inputs:
  cvt-version:
    description: 'CVT version to download'
    default: '0.3.0'

runs:
  using: 'composite'
  steps:
    - name: Download CVT CLI
      shell: bash
      run: |
        mkdir -p $GITHUB_WORKSPACE/bin
        curl -fsSL "https://github.com/sahina/cvt/releases/download/v${{ inputs.cvt-version }}/cvt_${{ inputs.cvt-version }}_linux_amd64.tar.gz" \
          | tar xz -C $GITHUB_WORKSPACE/bin cvt
        chmod +x $GITHUB_WORKSPACE/bin/cvt
        echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH

    - name: Verify CVT CLI
      shell: bash
      run: cvt version || cvt --help
